=== maroontress/maroontress.com/Sanctuary/1.0/sanctuary.dtd
<!-- This file was generated automatically.  DO NOT EDIT THIS FILE. -->

<!ELEMENT package (desc?)>
<!ATTLIST package name CDATA #REQUIRED>

<!ELEMENT class (namespace?, include*, define*, import*, export*, typedef*, (struct|union|enum)*, (method|abstractmethod)*, (globalvariable)*, desc?)>
<!ATTLIST class name CDATA #REQUIRED>
<!ATTLIST class package CDATA #REQUIRED>

<!ELEMENT interface (namespace?, method*, desc?)>
<!ATTLIST interface name CDATA #REQUIRED>
<!ATTLIST interface package CDATA #REQUIRED>

<!ELEMENT namespace EMPTY>

<!ELEMENT include EMPTY>
<!ATTLIST include file CDATA #REQUIRED>

<!ELEMENT import EMPTY>
<!ATTLIST import type (struct|union|enum) #REQUIRED>
<!ATTLIST import tag CDATA #REQUIRED>

<!ELEMENT export (desc?)>
<!ATTLIST export type (struct|union|enum) #REQUIRED>
<!ATTLIST export tag CDATA #REQUIRED>

<!ELEMENT define (macroparam*, variableparam?, macro?, desc?)>
<!ATTLIST define name CDATA #REQUIRED>

<!ELEMENT macroparam (desc?)>
<!ATTLIST macroparam name CDATA #REQUIRED>

<!ELEMENT macro (#PCDATA)>

<!ELEMENT typedef (desc?)>
<!ATTLIST typedef type CDATA #REQUIRED>
<!ATTLIST typedef name CDATA #REQUIRED>

<!ELEMENT method ((param+, variableparam?)?, modifier?, return?, desc?)>
<!ATTLIST method name CDATA #REQUIRED>

<!ELEMENT abstractmethod ((param+, variableparam?)?, modifier?, return?, desc?)>
<!ATTLIST abstractmethod name CDATA #REQUIRED>

<!ELEMENT param (desc?)>
<!ATTLIST param type CDATA #REQUIRED>
<!ATTLIST param name CDATA #REQUIRED>

<!ELEMENT variableparam EMPTY>

<!ELEMENT modifier EMPTY>
<!ATTLIST modifier code CDATA #REQUIRED>

<!ELEMENT return (desc?)>
<!ATTLIST return type CDATA #REQUIRED>

<!ELEMENT globalvariable (desc?)>
<!ATTLIST globalvariable type CDATA #REQUIRED>
<!ATTLIST globalvariable name CDATA #REQUIRED>

<!ENTITY % nest.group "member|structmember|unionmember|enummember|method">

<!ELEMENT struct ((%nest.group;)*, desc?)>
<!ATTLIST struct tag CDATA #IMPLIED>
<!ATTLIST struct alias CDATA #IMPLIED>

<!ELEMENT structmember ((%nest.group;)*, tag?, desc?)>
<!ATTLIST structmember tag CDATA #IMPLIED>
<!ATTLIST structmember name CDATA #REQUIRED>

<!ELEMENT union ((%nest.group;)*, desc?)>
<!ATTLIST union tag CDATA #IMPLIED>
<!ATTLIST union alias CDATA #IMPLIED>

<!ELEMENT unionmember ((%nest.group;)*, tag?, desc?)>
<!ATTLIST unionmember tag CDATA #IMPLIED>
<!ATTLIST unionmember name CDATA #REQUIRED>

<!ELEMENT enum (constant+, desc?)>
<!ATTLIST enum tag CDATA #IMPLIED>
<!ATTLIST enum alias CDATA #IMPLIED>

<!ELEMENT enummember (constant+, tag?, desc?)>
<!ATTLIST enummember tag CDATA #IMPLIED>
<!ATTLIST enummember name CDATA #REQUIRED>

<!ELEMENT member (desc?)>
<!ATTLIST member type CDATA #REQUIRED>
<!ATTLIST member name CDATA #REQUIRED>

<!ELEMENT constant (desc?)>
<!ATTLIST constant name CDATA #REQUIRED>
<!ATTLIST constant value CDATA #IMPLIED>

<!ELEMENT tag (desc?)>

<!ENTITY % inline.group "code|math|arg|em|a|hypertarget|hyperlink">

<!ELEMENT code (#PCDATA)>

<!ELEMENT math (#PCDATA)>

<!ELEMENT arg (#PCDATA)>

<!ELEMENT em (#PCDATA)>

<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA #REQUIRED>

<!ELEMENT hypertarget (#PCDATA)>
<!ATTLIST hypertarget label ID #REQUIRED>

<!ELEMENT hyperlink (#PCDATA)>
<!ATTLIST hyperlink label CDATA #IMPLIED>
<!ATTLIST hyperlink namespace CDATA #IMPLIED>

<!ENTITY % block.group "p|pre|see|note|ul">

<!ELEMENT p (#PCDATA|%inline.group;|brief)*>

<!ELEMENT see (#PCDATA|%inline.group;)*>

<!ELEMENT note (#PCDATA|%inline.group;)*>

<!ELEMENT ul (li+)>

<!ELEMENT li (#PCDATA|%inline.group;|%block.group;)*>

<!ELEMENT pre (#PCDATA)>

<!ELEMENT brief (#PCDATA|%inline.group;)*>

<!ELEMENT section (#PCDATA)>

<!ELEMENT desc (#PCDATA|%inline.group;|%block.group;|brief|section)*>

=== maroontress/maroontress.com/Sanctuary/r1/s2/foo/Description.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/1.0/sanctuary.dtd">
<class package="foo" name="Description">
  <namespace/>

  <struct tag="@">
    <member type="int" name="value">
      <desc>
        <brief>構造体のメンバのドキュメントの書き方を説明します。</brief>
        <p>このメンバの説明を記述します。</p>

        <section>メンバの説明中のセクション</section>
        <p>セクションはこのように展開されます。</p>
      </desc>
    </member>

    <method name="method">
      <param type="int" name="in">
	<desc>
          <brief>関数の引数のドキュメントの書き方を説明します。</brief>
          <p>この引数の説明を記述します。</p>

          <section>引数の説明中のセクション</section>
          <p>セクションはこのように展開されます。</p>
        </desc>
      </param>
      <return type="int">
	<desc>
          <brief>関数の戻り値のドキュメントの書き方を説明します。</brief>
          <p>この戻り値の説明を記述します。</p>

          <section>戻り値の説明中のセクション</section>
          <p>セクションはこのように展開されます。</p>
        </desc>
      </return>
      <desc>
        <brief>構造体の関数ポインタ型メンバのドキュメントの書き方を説明します。</brief>
        <p>この関数ポインタ型メンバの説明を記述します。</p>

        <section>関数ポインタ型メンバの説明中のセクション</section>
        <p>セクションはこのように展開されます。</p>
      </desc>
    </method>

    <desc>
      <brief>構造体のドキュメントの書き方を説明します。</brief>
      <p>この構造体の説明を記述します。</p>

      <section>構造体の説明中のセクション</section>
      <p>セクションはこのように展開されます。</p>
    </desc>
  </struct>

  <method name="method">
    <param type="int" name="in">
      <desc>
        <brief>関数の引数のドキュメントの書き方を説明します。</brief>
        <p>この引数の説明を記述します。</p>

        <section>引数の説明中のセクション</section>
        <p>セクションはこのように展開されます。</p>
      </desc>
    </param>
    <return type="int">
      <desc>
        <brief>関数の戻り値のドキュメントの書き方を説明します。</brief>
        <p>この戻り値の説明を記述します。</p>

        <section>戻り値の説明中のセクション</section>
        <p>セクションはこのように展開されます。</p>
      </desc>
    </return>
    <desc>
      <brief>関数のドキュメントの書き方を説明します。</brief>
      <p>この関数の説明を記述します。</p>

      <section>関数の説明中のセクション</section>
      <p>セクションはこのように展開されます。</p>
    </desc>
  </method>

  <desc>
    <brief>Descriptionクラスはドキュメントの書き方を提供します。</brief>
    <p><hypertarget label="target">このクラスの説明</hypertarget>を記述します。</p>

    <section>クラスの説明中のセクション</section>
    <p>セクションはこのように展開されます。</p>

    <section>文字の装飾</section>
    <p>強調したい語句は<em>このように</em>なります。</p>
    <p>タイプライタ体は<code>keyword</code>のようになります。</p>
    <p>引数やパラメータは<arg>argument</arg>のようになります。</p>
    <p>マイナス記号は<math>-1</math>のようになります。</p>

    <section>ハイパーリンク</section>
    <p>URLへのリンクは<a href="http://www.example.com/">http://www.example.com/</a>のようになります。</p>
    <p>同一クラス内へのリンクは<hyperlink label="target">このように</hyperlink>なります。</p>
    <p>他のクラスへのリンクは<hyperlink namespace="com_example.Integer">com_example_Integerクラス</hyperlink>のように、パッケージの文書へのリンクは<hyperlink namespace="com_example">com_exampleパッケージ</hyperlink>のようになります。</p>

    <section>リスト</section>
    <p>リストは次のように展開されます。</p>
    <ul>
      <li>リストの項目1</li>
      <li>リストの項目2</li>
    </ul>

    <see>参照先の項目を記述します。</see>

    <note>注意すべき項目を記述します。</note>

    <!--
    <p><hyperlink namespace="foo.Bool">foo_Boolクラス</hyperlink></p>
    <p><hyperlink namespace="foo.Bool" label="target">foo_Boolクラスの"target"</hyperlink></p>
    <p><hyperlink namespace="foo">fooパッケージ</hyperlink></p>
    <p><hyperlink namespace="foo" label="target">fooパッケージの"target"</hyperlink></p>
    <p><hyperlink>このクラス（foo_Description）そのもの</hyperlink></p>
    <p><hyperlink label="target">このクラスの"target"</hyperlink></p>
    -->
  </desc>
</class>

=== maroontress/maroontress.com/Sanctuary/r2/s2/foo/OpaqueStruct.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/2.0/sanctuary.dtd">
<class package="foo" name="OpaqueStruct">
  <namespace/>

  <export type="struct" tag="@">
    <desc>
      <brief>ある構造体です。</brief>
      <p>構造体の詳細は隠蔽されています。</p>
    </desc>
  </export>

  <method name="new">
    <param type="struct another_Class *" name="s">
      <desc>別のクラスで記述されている構造体のポインタ</desc>
    </param>

    <return type="struct @ *">
      <desc>インスタンスのポインタ</desc>
    </return>

    <desc><brief>別のクラスで定義されている構造体のポインタ型から、不透明なデータ型のインスタンスを生成します。</brief></desc>
  </method>

  <desc><brief>export要素の使用例を提供します。</brief></desc>
</class>

=== maroontress/maroontress.com/Sanctuary/r1/s2/bar/FileFactory.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/1.0/sanctuary.dtd">
<class package="bar" name="FileFactory">
  <namespace/>

  <include file="stdio.h"/>

  <method name="open">
    <param type="const void *" name="cookie">
      <desc><hyperlink namespace="bar.Openable">Openableインタフェース</hyperlink>のインスタンス</desc>
    </param>

    <param type="int (*#)(void *, char *, int)" name="readfn">
      <desc>see bar_Openable_readfn()</desc>
    </param>

    <param type="int (*#)(void *, const char *, int)" name="writefn">
      <desc>see bar_Openable_writefn()</desc>
    </param>

    <param type="fpos_t (*#)(void *, fpos_t, int)" name="seekfn">
      <desc>see bar_Openable_seekfn()</desc>
    </param>

    <param type="int (*#)(void *)" name="closefn">
      <desc>see bar_Openable_closefn()</desc>
    </param>

    <return type="foo_File *">
      <desc><hyperlink namespace="foo.File">Fileクラス</hyperlink>のインスタンス、またはNULL</desc>
    </return>

    <desc>
      <brief>OpenableインタフェースからFileクラスのインスタンスを生成します。</brief>
      <p>生成できないときはNULLを返します。</p>
    </desc>
  </method>

  <desc><brief>Fileクラスのインスタンスを生成する機能を提供します。</brief></desc>
</class>

=== maroontress/maroontress.com/Sanctuary/r2/s2/com/example/StringList.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/2.0/sanctuary.dtd">
<class package="com_example" name="StringList">
  <namespace/>

  <struct tag="@" alias="@">
    <member type="struct @ *" name="next">
      <desc>
        <brief>リストの次の構造体を指します。</brief>
        <p>リストの最後の構造体の場合、NULLになります。</p>
      </desc>
    </member>

    <member type="char *" name="value">
      <desc>
        <brief>保持している文字列です。</brief>
      </desc>
    </member>

    <desc>
      <brief>文字列のリストとなる構造体です。</brief>
      <p>構造体のリンクでリストを実現します。</p>
    </desc>
  </struct>

  <desc>
    <brief>自己参照する構造体の例として文字列のリストを表すデータ型を提供します。</brief>
    <p>操作は省略されています。</p>
  </desc>
</class>

=== maroontress/maroontress.com/Sanctuary/r2/s2/foo/FunctionMember.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/2.0/sanctuary.dtd">
<class package="foo" name="FunctionMember">
  <namespace/>

  <struct tag="@"> 
    <methodmember name="func">
      <param type="int" name="in">
	<desc>入力値</desc>
      </param>

      <return type="int">
	<desc>出力値</desc>
      </return>

      <desc><brief>入力に対応する出力を返します。</brief></desc>
    </methodmember>

    <desc><brief>関数ポインタ型のメンバをもつ構造体です。</brief></desc>
  </struct>

  <desc><brief>関数ポインタ型のメンバをもつ構造体の例を提供します。</brief></desc>
</class>

=== maroontress/maroontress.com/Sanctuary/r1/s1/com/example/Integer0.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/1.0/sanctuary.dtd">
<class package="com_example" name="Integer0">
  <define name="com_example_Integer0_MAX">
    <macro>0x7fffffff</macro>
  </define>

  <define name="com_example_Integer0_MIN">
    <macro>(-0x7fffffff - 1)</macro>
  </define>

  <typedef type="int" name="com_example_Integer0_t"/>

  <struct tag="com_example_Integer0">
    <member type="com_example_Integer0_t" name="value"/>
  </struct>

  <method name="com_example_Integer0_new">
    <param type="com_example_Integer0_t" name="i"/>
    <return type="struct com_example_Integer0 *"/>
  </method>

  <method name="com_example_Integer0_delete">
    <param type="struct com_example_Integer0 *" name="i"/>
  </method>

  <method name="com_example_Integer0_set">
    <param type="struct com_example_Integer0 *" name="i"/>
    <param type="com_example_Integer0_t" name="value"/>
  </method>

  <method name="com_example_Integer0_get">
    <param type="struct com_example_Integer0 *" name="i"/>
    <return type="com_example_Integer0_t"/>
  </method>
</class>

=== maroontress/maroontress.com/Sanctuary/r1/s1/com/example/Integer1.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/1.0/sanctuary.dtd">
<class package="com_example" name="Integer1">
  <define name="@_MAX">
    <macro>0x7fffffff</macro>
  </define>

  <define name="@_MIN">
    <macro>(-0x7fffffff - 1)</macro>
  </define>

  <typedef type="int" name="@_t"/>

  <struct tag="@">
    <member type="@_t" name="value"/>
  </struct>

  <method name="@_new">
    <param type="@_t" name="i"/>
    <return type="struct @ *"/>
  </method>

  <method name="@_delete">
    <param type="struct @ *" name="i"/>
  </method>

  <method name="@_set">
    <param type="struct @ *" name="i"/>
    <param type="@_t" name="value"/>
  </method>

  <method name="@_get">
    <param type="struct @ *" name="i"/>
    <return type="@_t"/>
  </method>
</class>

=== maroontress/maroontress.com/Sanctuary/r1/s2/bar/Openable.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE interface SYSTEM "http://maroontress.com/Sanctuary/1.0/sanctuary.dtd" [
  <!ENTITY cookieParam '
    <param type="void *" name="cookie">
      <desc>このインスタンスのポインタ</desc>
    </param>'>
]>
<interface package="bar" name="Openable">
  <namespace/>

  <method name="readfn">
    &cookieParam;

    <param type="char *" name="data">
      <desc>読み込むデータを格納する領域のポインタ</desc>
    </param>

    <param type="int" name="size">
      <desc><arg>data</arg>のサイズ</desc>
    </param>

    <return type="int">
      <desc>成功した場合は実際に読み込んだデータのサイズを返します。ファイルの最後の場合は0を返します。そうでなければ<math>-1</math>を返します。</desc>
    </return>

    <desc><brief>ファイルからデータを読み込みます。</brief></desc>
  </method>

  <method name="writefn">
    &cookieParam;

    <param type="const char *" name="data">
      <desc>書き込むデータを格納した領域のポインタ</desc>
    </param>

    <param type="int" name="size">
      <desc><arg>data</arg>のサイズ</desc>
    </param>

    <return type="int">
      <desc>成功した場合は書き込んだデータのサイズを返します。そうでなければ<math>-1</math>を返します。</desc>
    </return>

    <desc><brief>ファイルにデータを書き込みます。</brief></desc>
  </method>

  <method name="seekfn">
    &cookieParam;

    <param type="fpos_t" name="offset">
      <desc>ファイルのオフセット</desc>
    </param>

    <param type="int" name="whence">
      <desc><arg>offset</arg>の起点</desc>
    </param>

    <return type="fpos_t">
      <desc>成功した場合はファイルの先頭からのオフセットを返します。そうでなければ<math>-1</math>を返します。</desc>
    </return>

    <desc>
      <brief>ファイルのオフセットを変更します。</brief>
      <p><arg>whence</arg>の値には<code>foo_Whence_SET</code>、<code>foo_Whence_SET</code>、<code>foo_Whence_END</code>のいずれかを指定します。</p>
    </desc>
  </method>

  <method name="closefn">
    &cookieParam;

    <return type="int">
      <desc>成功した場合は0を返します。そうでなければ<math>-1</math>を返します。</desc>
    </return>

    <desc><brief>ファイルをクローズします。</brief></desc>
  </method>

  <desc><brief>オープン可能なインタフェースの記述例を提供します。</brief></desc>
</interface>
