=== maroontress/maroontress.com/Sanctuary/1.0/sanctuary.dtd
<!-- This file was generated automatically.  DO NOT EDIT THIS FILE. -->

<!ELEMENT package (desc?)>
<!ATTLIST package name CDATA #REQUIRED>

<!ELEMENT class (namespace?, include*, define*, import*, export*, typedef*, (struct|union|enum)*, (method|abstractmethod)*, (globalvariable)*, desc?)>
<!ATTLIST class name CDATA #REQUIRED>
<!ATTLIST class package CDATA #REQUIRED>

<!ELEMENT interface (namespace?, method*, desc?)>
<!ATTLIST interface name CDATA #REQUIRED>
<!ATTLIST interface package CDATA #REQUIRED>

<!ELEMENT namespace EMPTY>

<!ELEMENT include EMPTY>
<!ATTLIST include file CDATA #REQUIRED>

<!ELEMENT import EMPTY>
<!ATTLIST import type (struct|union|enum) #REQUIRED>
<!ATTLIST import tag CDATA #REQUIRED>

<!ELEMENT export (desc?)>
<!ATTLIST export type (struct|union|enum) #REQUIRED>
<!ATTLIST export tag CDATA #REQUIRED>

<!ELEMENT define (macroparam*, variableparam?, macro?, desc?)>
<!ATTLIST define name CDATA #REQUIRED>

<!ELEMENT macroparam (desc?)>
<!ATTLIST macroparam name CDATA #REQUIRED>

<!ELEMENT macro (#PCDATA)>

<!ELEMENT typedef (desc?)>
<!ATTLIST typedef type CDATA #REQUIRED>
<!ATTLIST typedef name CDATA #REQUIRED>

<!ELEMENT method ((param+, variableparam?)?, modifier?, return?, desc?)>
<!ATTLIST method name CDATA #REQUIRED>

<!ELEMENT abstractmethod ((param+, variableparam?)?, modifier?, return?, desc?)>
<!ATTLIST abstractmethod name CDATA #REQUIRED>

<!ELEMENT param (desc?)>
<!ATTLIST param type CDATA #REQUIRED>
<!ATTLIST param name CDATA #REQUIRED>

<!ELEMENT variableparam EMPTY>

<!ELEMENT modifier EMPTY>
<!ATTLIST modifier code CDATA #REQUIRED>

<!ELEMENT return (desc?)>
<!ATTLIST return type CDATA #REQUIRED>

<!ELEMENT globalvariable (desc?)>
<!ATTLIST globalvariable type CDATA #REQUIRED>
<!ATTLIST globalvariable name CDATA #REQUIRED>

<!ENTITY % nest.group "member|structmember|unionmember|enummember|method">

<!ELEMENT struct ((%nest.group;)*, desc?)>
<!ATTLIST struct tag CDATA #IMPLIED>
<!ATTLIST struct alias CDATA #IMPLIED>

<!ELEMENT structmember ((%nest.group;)*, tag?, desc?)>
<!ATTLIST structmember tag CDATA #IMPLIED>
<!ATTLIST structmember name CDATA #REQUIRED>

<!ELEMENT union ((%nest.group;)*, desc?)>
<!ATTLIST union tag CDATA #IMPLIED>
<!ATTLIST union alias CDATA #IMPLIED>

<!ELEMENT unionmember ((%nest.group;)*, tag?, desc?)>
<!ATTLIST unionmember tag CDATA #IMPLIED>
<!ATTLIST unionmember name CDATA #REQUIRED>

<!ELEMENT enum (constant+, desc?)>
<!ATTLIST enum tag CDATA #IMPLIED>
<!ATTLIST enum alias CDATA #IMPLIED>

<!ELEMENT enummember (constant+, tag?, desc?)>
<!ATTLIST enummember tag CDATA #IMPLIED>
<!ATTLIST enummember name CDATA #REQUIRED>

<!ELEMENT member (desc?)>
<!ATTLIST member type CDATA #REQUIRED>
<!ATTLIST member name CDATA #REQUIRED>

<!ELEMENT constant (desc?)>
<!ATTLIST constant name CDATA #REQUIRED>
<!ATTLIST constant value CDATA #IMPLIED>

<!ELEMENT tag (desc?)>

<!ENTITY % inline.group "code|math|arg|em|a|hypertarget|hyperlink">

<!ELEMENT code (#PCDATA)>

<!ELEMENT math (#PCDATA)>

<!ELEMENT arg (#PCDATA)>

<!ELEMENT em (#PCDATA)>

<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA #REQUIRED>

<!ELEMENT hypertarget (#PCDATA)>
<!ATTLIST hypertarget label ID #REQUIRED>

<!ELEMENT hyperlink (#PCDATA)>
<!ATTLIST hyperlink label CDATA #IMPLIED>
<!ATTLIST hyperlink namespace CDATA #IMPLIED>

<!ENTITY % block.group "p|pre|see|note|ul">

<!ELEMENT p (#PCDATA|%inline.group;|brief)*>

<!ELEMENT see (#PCDATA|%inline.group;)*>

<!ELEMENT note (#PCDATA|%inline.group;)*>

<!ELEMENT ul (li+)>

<!ELEMENT li (#PCDATA|%inline.group;|%block.group;)*>

<!ELEMENT pre (#PCDATA)>

<!ELEMENT brief (#PCDATA|%inline.group;)*>

<!ELEMENT section (#PCDATA)>

<!ELEMENT desc (#PCDATA|%inline.group;|%block.group;|brief|section)*>

=== maroontress/maroontress.com/Sanctuary/r1/s2/foo/Printer.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/1.0/sanctuary.dtd">
<class package="foo" name="Printer">
  <namespace/>

  <method name="print">
    <param type="const char *" name="format">
      <desc>フォーマット（printf(3)を参照してください）</desc>
    </param>

    <variableparam/>

    <return type="int">
      <desc>出力したバイト数</desc>
    </return>

    <desc>
      <brief>指定したフォーマットに整形した文字列を出力します。</brief>
      <p>いわゆるprintf()ライクな関数です。</p>
    </desc>
  </method>

  <desc><brief>variableparam要素の使用例を提供します。</brief></desc>
</class>

=== maroontress/maroontress.com/Sanctuary/r1/s1/com/example/Integer3.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/1.0/sanctuary.dtd" [
  <!ENTITY thisParam '<param type="struct @ *" name="i"/>'>
]>
<class package="com_example" name="Integer3">
  <namespace/>

  <define name="MAX">
    <macro>0x7fffffff</macro>
  </define>

  <define name="MIN">
    <macro>(-0x7fffffff - 1)</macro>
  </define>

  <typedef type="int" name="t"/>

  <struct tag="@">
    <member type="@_t" name="value"/>
  </struct>

  <method name="new">
    <param type="@_t" name="i"/>
    <return type="struct @ *"/>
  </method>

  <method name="delete">
    &thisParam;
  </method>

  <method name="set">
    &thisParam;
    <param type="@_t" name="value"/>
  </method>

  <method name="get">
    &thisParam;
    <return type="@_t"/>
  </method>
</class>

=== maroontress/maroontress.com/Sanctuary/r1/s2/bar/Splint.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/1.0/sanctuary.dtd">
<class package="bar" name="Splint">
  <namespace/>

  <export type="struct" tag="@">
    <desc><brief>Splint構造体です。</brief><p>不透明な構造体です。</p></desc>
  </export>

  <method name="initialize">
    <param type="/*@out@*/ struct @ *" name="s">
      <desc>初期化するSplint構造体のポインタ</desc>
    </param>

    <desc><brief>Splint構造体を初期化します。</brief></desc>
  </method>

  <desc><brief>Splintのアノテーションを埋め込んだ例を提供します。</brief></desc>
</class>

=== maroontress/maroontress.com/Sanctuary/r2/s2/foo/Opaque.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/2.0/sanctuary.dtd">
<class package="foo" name="Opaque">
  <namespace/>

  <define name="TYPE">
    <macro>struct another_Class *</macro>
    <desc>
      <brief>コンストラクタの引数の型です。</brief>
      <p>型の詳細は隠蔽されています。</p>
    </desc>
  </define>

  <import type="struct" tag="another_Class"/>

  <typedef type="struct @_ *" name="@">
    <desc>
      <brief>ある構造体のポインタ型です。</brief>
      <p>構造体の詳細は隠蔽されています。</p>
    </desc>
  </typedef>

  <method name="new">
    <param type="@_TYPE" name="s">
      <desc>別のクラスで記述されている構造体のポインタ</desc>
    </param>

    <return type="@">
      <desc>インスタンスのポインタ</desc>
    </return>

    <desc><brief>別のクラスで定義されている構造体のポインタ型から、不透明なデータ型のインスタンスを生成します。</brief></desc>
  </method>

  <desc><brief>import要素の使用例を提供します。</brief></desc>
</class>

=== maroontress/maroontress.com/Sanctuary/r1/s2/foo/Whence.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/1.0/sanctuary.dtd">
<class package="foo" name="Whence">
  <namespace/>

  <enum tag="@">
    <constant name="SET" value="1">
      <desc><brief>ファイル先頭からのオフセットを表します。</brief></desc>
    </constant>

    <constant name="CUR">
      <desc><brief>現在のファイル位置からのオフセットを表します。</brief></desc>
    </constant>

    <constant name="END">
      <desc><brief>ファイル末尾からのオフセットを表します。</brief></desc>
    </constant>

    <desc>
      <brief>ファイルをシークする際にオフセットの基点を指定する列挙型です。</brief>
    </desc>
  </enum>

  <desc>
    <brief>ファイルのシークに必要な指令を提供します。</brief>
    <p>lseek(2)の引数whenceをenumで表現してみました。</p>
  </desc>
</class>

=== maroontress/maroontress.com/Sanctuary/r2/s1/com/example/Integer2.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/2.0/sanctuary.dtd">
<class package="com_example" name="Integer2">
  <namespace/>

  <define name="MAX">
    <macro>0x7fffffff</macro>
  </define>

  <define name="MIN">
    <macro>(-0x7fffffff - 1)</macro>
  </define>

  <typedef type="int" name="t"/>

  <struct tag="@">
    <member type="@_t" name="value"/>
  </struct>

  <method name="new">
    <param type="@_t" name="i"/>
    <return type="struct @ *"/>
  </method>

  <method name="delete">
    <param type="struct @ *" name="i"/>
  </method>

  <method name="set">
    <param type="struct @ *" name="i"/>
    <param type="@_t" name="value"/>
  </method>

  <method name="get">
    <param type="struct @ *" name="i"/>
    <return type="@_t"/>
  </method>
</class>

=== maroontress/maroontress.com/Sanctuary/r2/s2/foo/Preference.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/2.0/sanctuary.dtd" [
 <!ENTITY maxParameters '3'>
]>
<class package="foo" name="Preference">
  <namespace/>

  <globalvariable type="char *" name="option">
    <desc><brief>オプションを表す文字列です。</brief></desc>
  </globalvariable>

  <globalvariable type="int #[&maxParameters;]" name="parameters">
    <desc>
      <brief>パラメータを表す整数の配列です。</brief>
      <p>配列の要素数は&maxParameters;です。</p>
    </desc>
  </globalvariable>

  <desc>
    <brief>globalvariable要素の使用例を提供します。</brief>
    <p>グローバル変数を使用するべきでありません。設定、取得メソッドをもつシングルトンパターンのクラスを用意すべきです。</p>
  </desc>
</class>

=== maroontress/maroontress.com/Sanctuary/r1/s2/foo/Time.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/1.0/sanctuary.dtd">
<class package="foo" name="Time">
  <namespace/>

  <define name="add">
    <macroparam name="tvp">
      <desc>timeval構造体のポインタ</desc>
    </macroparam>

    <macroparam name="uvp">
      <desc>timeval構造体のポインタ</desc>
    </macroparam>

    <macroparam name="vvp">
      <desc>和を格納するtimeval構造体のポインタ</desc>
    </macroparam>

    <macro>
do {
  (vvp)->tv_sec = (tvp)->tv_sec + (uvp)->tv_sec;
  (vvp)->tv_usec = (tvp)->tv_usec + (uvp)->tv_usec;
  if ((vvp)->tv_usec >= 1000000) {
    (vvp)->tv_sec++;
    (vvp)->tv_usec -= 1000000;
  }
} while (0)
    </macro>

    <desc>
      <brief>timeval構造体の和を求めます。</brief>
      <p><arg>tvp</arg> + <arg>uvp</arg>の値を計算し、<arg>vvp</arg>に格納します。</p>
      <p><arg>tvp</arg>, <arg>uvp</arg>, <arg>vvp</arg>はtimeval構造体のポインタでなければなりません。</p>
    </desc>
  </define>

  <desc>
    <brief>timeval構造体を演算する操作を提供します。</brief>
  </desc>
</class>
