=== maroontress/maroontress.com/Sanctuary/1.0/sanctuary.dtd
<!-- This file was generated automatically.  DO NOT EDIT THIS FILE. -->

<!ELEMENT package (desc?)>
<!ATTLIST package name CDATA #REQUIRED>

<!ELEMENT class (namespace?, include*, define*, import*, export*, typedef*, (struct|union|enum)*, (method|abstractmethod)*, (globalvariable)*, desc?)>
<!ATTLIST class name CDATA #REQUIRED>
<!ATTLIST class package CDATA #REQUIRED>

<!ELEMENT interface (namespace?, method*, desc?)>
<!ATTLIST interface name CDATA #REQUIRED>
<!ATTLIST interface package CDATA #REQUIRED>

<!ELEMENT namespace EMPTY>

<!ELEMENT include EMPTY>
<!ATTLIST include file CDATA #REQUIRED>

<!ELEMENT import EMPTY>
<!ATTLIST import type (struct|union|enum) #REQUIRED>
<!ATTLIST import tag CDATA #REQUIRED>

<!ELEMENT export (desc?)>
<!ATTLIST export type (struct|union|enum) #REQUIRED>
<!ATTLIST export tag CDATA #REQUIRED>

<!ELEMENT define (macroparam*, variableparam?, macro?, desc?)>
<!ATTLIST define name CDATA #REQUIRED>

<!ELEMENT macroparam (desc?)>
<!ATTLIST macroparam name CDATA #REQUIRED>

<!ELEMENT macro (#PCDATA)>

<!ELEMENT typedef (desc?)>
<!ATTLIST typedef type CDATA #REQUIRED>
<!ATTLIST typedef name CDATA #REQUIRED>

<!ELEMENT method ((param+, variableparam?)?, modifier?, return?, desc?)>
<!ATTLIST method name CDATA #REQUIRED>

<!ELEMENT abstractmethod ((param+, variableparam?)?, modifier?, return?, desc?)>
<!ATTLIST abstractmethod name CDATA #REQUIRED>

<!ELEMENT param (desc?)>
<!ATTLIST param type CDATA #REQUIRED>
<!ATTLIST param name CDATA #REQUIRED>

<!ELEMENT variableparam EMPTY>

<!ELEMENT modifier EMPTY>
<!ATTLIST modifier code CDATA #REQUIRED>

<!ELEMENT return (desc?)>
<!ATTLIST return type CDATA #REQUIRED>

<!ELEMENT globalvariable (desc?)>
<!ATTLIST globalvariable type CDATA #REQUIRED>
<!ATTLIST globalvariable name CDATA #REQUIRED>

<!ENTITY % nest.group "member|structmember|unionmember|enummember|method">

<!ELEMENT struct ((%nest.group;)*, desc?)>
<!ATTLIST struct tag CDATA #IMPLIED>
<!ATTLIST struct alias CDATA #IMPLIED>

<!ELEMENT structmember ((%nest.group;)*, tag?, desc?)>
<!ATTLIST structmember tag CDATA #IMPLIED>
<!ATTLIST structmember name CDATA #REQUIRED>

<!ELEMENT union ((%nest.group;)*, desc?)>
<!ATTLIST union tag CDATA #IMPLIED>
<!ATTLIST union alias CDATA #IMPLIED>

<!ELEMENT unionmember ((%nest.group;)*, tag?, desc?)>
<!ATTLIST unionmember tag CDATA #IMPLIED>
<!ATTLIST unionmember name CDATA #REQUIRED>

<!ELEMENT enum (constant+, desc?)>
<!ATTLIST enum tag CDATA #IMPLIED>
<!ATTLIST enum alias CDATA #IMPLIED>

<!ELEMENT enummember (constant+, tag?, desc?)>
<!ATTLIST enummember tag CDATA #IMPLIED>
<!ATTLIST enummember name CDATA #REQUIRED>

<!ELEMENT member (desc?)>
<!ATTLIST member type CDATA #REQUIRED>
<!ATTLIST member name CDATA #REQUIRED>

<!ELEMENT constant (desc?)>
<!ATTLIST constant name CDATA #REQUIRED>
<!ATTLIST constant value CDATA #IMPLIED>

<!ELEMENT tag (desc?)>

<!ENTITY % inline.group "code|math|arg|em|a|hypertarget|hyperlink">

<!ELEMENT code (#PCDATA)>

<!ELEMENT math (#PCDATA)>

<!ELEMENT arg (#PCDATA)>

<!ELEMENT em (#PCDATA)>

<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA #REQUIRED>

<!ELEMENT hypertarget (#PCDATA)>
<!ATTLIST hypertarget label ID #REQUIRED>

<!ELEMENT hyperlink (#PCDATA)>
<!ATTLIST hyperlink label CDATA #IMPLIED>
<!ATTLIST hyperlink namespace CDATA #IMPLIED>

<!ENTITY % block.group "p|pre|see|note|ul">

<!ELEMENT p (#PCDATA|%inline.group;|brief)*>

<!ELEMENT see (#PCDATA|%inline.group;)*>

<!ELEMENT note (#PCDATA|%inline.group;)*>

<!ELEMENT ul (li+)>

<!ELEMENT li (#PCDATA|%inline.group;|%block.group;)*>

<!ELEMENT pre (#PCDATA)>

<!ELEMENT brief (#PCDATA|%inline.group;)*>

<!ELEMENT section (#PCDATA)>

<!ELEMENT desc (#PCDATA|%inline.group;|%block.group;|brief|section)*>

=== maroontress/maroontress.com/Sanctuary/r1/s2/foo/Union.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/1.0/sanctuary.dtd">
<class package="foo" name="Union">
  <namespace/>

  <union tag="IntDouble">
    <member type="int #[2]" name="i">
      <desc><brief>int型の配列としてアクセスします。</brief></desc>
    </member>

    <member type="double" name="d">
      <desc><brief>double型としてアクセスします。</brief></desc>
    </member>

    <desc><brief>intの配列（要素数2）とdoubleの共用体です。</brief></desc>
  </union>

  <union alias="UCharUInt">
    <member type="unsigned char #[4]" name="c">
      <desc><brief>unsigned char型の配列としてアクセスします。</brief></desc>
    </member>

    <member type="unsigned int" name="i">
      <desc><brief>unsigned int型としてアクセスします。</brief></desc>
    </member>

    <desc><brief>unsigned charの配列（要素数4）とunsigned intの共用体です。</brief></desc>
  </union>

  <desc>
    <brief>intとdouble、unsigned intとunsigned charのビットマップを相互に変換する機能を提供します。</brief>
  </desc>
</class>

=== maroontress/maroontress.com/Sanctuary/r2/s2/foo/NestedStruct.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/2.0/sanctuary.dtd">
<class package="foo" name="NestedStruct">
  <namespace/>

  <struct tag="Outer"> 
    <structmember name="s1">
      <member type="int" name="i">
	<desc><brief>何かの整数値です。</brief></desc>
      </member>

      <tag>
        <desc>
          <brief>匿名の構造体です。</brief>
	  <p>匿名の構造体には、便宜上、仮の名前が付けられます。仮の名前は@に続くユニークなID（整数値）となります。</p>
          <p><em>匿名の構造体の説明をここに記述します。</em></p>
        </desc>
      </tag>

      <desc>
        <brief>型が「匿名の構造体」のメンバです。</brief>
        <p><em>メンバs1の説明をここに記述します。</em></p>
      </desc>
    </structmember>

    <structmember tag="Inner" name="s2">
      <member type="int" name="i">
	<desc><brief>何かの整数値です。</brief></desc>
      </member>

      <tag>
        <desc>
          <brief>構造体のメンバとして定義される構造体です。</brief>
          <p>この構造体はトップレベルで定義された場合と同様に扱えます。</p>
          <p><em>構造体Innerの説明をここに記述します。</em></p>
        </desc>
      </tag>

      <desc>
        <brief>型が「foo_NestedStruct_Inner構造体」のメンバです。</brief>
        <p><em>メンバs2の説明をここに記述します。</em></p>
      </desc>
    </structmember>

    <desc><brief>メンバとして構造体を定義する構造体です。</brief></desc>
  </struct>

  <desc><brief>ネストする構造体の例を提供します。</brief></desc>
</class>

=== maroontress/maroontress.com/Sanctuary/r1/s2/foo/File.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/1.0/sanctuary.dtd">
<class package="foo" name="File">
  <namespace/>

  <include file="stdio.h"/>

  <struct alias="@">
    <member type="FILE *" name="file">
      <desc><brief>標準入出力ライブラリのFILE型へのポインタです。</brief></desc>
    </member>

    <desc><brief>Fileクラスのインスタンスとなる構造体です。</brief></desc>
  </struct>

  <method name="new">
    <param type="FILE *" name="file">
      <desc>標準入出力ライブラリのFILE型へのポインタ</desc>
    </param>

    <return type="@ *">
      <desc>Fileクラスのインスタンス、またはNULL</desc>
    </return>

    <desc>
      <brief>Fileクラスのインスタンスを生成します。</brief>
      <p>生成できないときはNULLを返します。</p>
    </desc>
  </method>

  <desc>
    <brief>include要素の使用例を提供します。</brief>
    <p>include要素はドキュメントに影響を与えません。</p>
  </desc>
</class>

=== maroontress/maroontress.com/Sanctuary/r2/s2/bar/Modifier.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/2.0/sanctuary.dtd">
<class package="bar" name="Modifier">
  <namespace/>

  <method name="abort">
    <modifier code="__attribute__((noreturn))"/>
    <desc><brief>コアをダンプして強制終了します。</brief></desc>
  </method>

  <method name="square">
    <param type="int" name="value">
      <desc>整数値</desc>
    </param>

    <modifier code="__attribute__((const))"/>

    <return type="int">
      <desc><arg>value</arg>の自乗の値</desc>
    </return>

    <desc><brief>自乗の値を返します。</brief></desc>
  </method>

  <desc><brief>修飾子の例を提供します。</brief></desc>
</class>

=== maroontress/maroontress.com/Sanctuary/r2/s1/com/example/Integer4.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/2.0/sanctuary.dtd" [
  <!ENTITY thisParam '
    <param type="struct @ *" name="i">
      <desc>Integer4クラスのインスタンス</desc>
    </param>
  '>
]>
<class package="com_example" name="Integer4">
  <namespace/>

  <define name="MAX">
    <macro>0x7fffffff</macro>
    <desc><brief>整数の最大値です。</brief></desc>
  </define>

  <define name="MIN">
    <macro>(-0x7fffffff - 1)</macro>
    <desc><brief>整数の最小値です。</brief></desc>
  </define>

  <typedef type="int" name="t">
    <desc><brief>整数値を表す型です。</brief></desc>
  </typedef>

  <struct tag="@">
    <member type="@_t" name="value">
      <desc><brief>現在の整数値を保持します。</brief></desc>
    </member>

    <desc>
      <brief>Integer4クラスのインスタンスとなる構造体です。</brief>
      <p>整数を保持します。</p>
    </desc>
  </struct>

  <method name="new">
    <param type="@_t" name="i">
      <desc>インスタンスの初期化</desc>
    </param>

    <return type="struct @ *">
      <desc>生成したインスタンス、または<code>NULL</code></desc>
    </return>

    <desc>
      <brief>Integer4クラスのインスタンスを生成します。</brief>
      <p>生成できないときはNULLを返します。</p>
    </desc>
  </method>

  <method name="delete">
    &thisParam;

    <desc>
      <brief>Integerクラスのインスタンスを破壊します。</brief>
      <p><arg>i</arg>が<code>NULL</code>のときは何もしません。</p>
    </desc>
  </method>

  <method name="set">
    &thisParam;

    <param type="@_t" name="value">
      <desc>整数値</desc>
    </param>

    <desc><brief>整数値を設定します。</brief></desc>
  </method>

  <method name="get">
    &thisParam;

    <return type="@_t">
      <desc>整数値</desc>
    </return>

    <desc><brief>整数値を取得します。</brief></desc>
  </method>

  <desc>
    <brief>整数値を表す型と、その型への操作を提供します。</brief>
    <p>チュートリアル以外に用途はありません。</p>
  </desc>
</class>

=== maroontress/maroontress.com/Sanctuary/r2/s2/com/example/Double.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/2.0/sanctuary.dtd" [
  <!ENTITY thisParam '
    <param type="@ *" name="d">
      <desc>Doubleクラスのインスタンス</desc>
    </param>
  '>
]>
<class package="com_example" name="Double">
  <namespace/>

  <struct alias="@">
    <member type="double" name="value">
      <desc>
        <brief>現在の実数値を保持します。</brief>
      </desc>
    </member>

    <desc>
      <brief>Doubleクラスのインスタンスとなる構造体です。</brief>
      <p>実数を保持します。</p>
    </desc>
  </struct>

  <method name="new">
    <param type="double" name="value">
      <desc>初期値となる実数値</desc>
    </param>

    <return type="@ *">
      <desc>Doubleクラスのインスタンス、またはNULL</desc>
    </return>

    <desc>
      <brief>Doubleクラスのインスタンスを生成します。</brief>
      <p>生成できないときはNULLを返します。</p>
    </desc>
  </method>

  <method name="delete">
    &thisParam;

    <desc>
      <brief>Doubleクラスのインスタンスを破壊します。</brief>
    </desc>
  </method>

  <method name="set">
    &thisParam;

    <param type="double" name="value">
      <desc>実数値</desc>
    </param>

    <desc>
      <brief>実数値を設定します。</brief>
    </desc>
  </method>

  <method name="get">
    &thisParam;

    <return type="double">
      <desc>実数値</desc>
    </return>

    <desc>
      <brief>実数値を取得します。</brief>
    </desc>
  </method>

  <desc>
    <brief>実数値を表す型と、その型への操作を提供します。</brief>
    <p><hyperlink namespace="com_example.Integer">Integerクラス</hyperlink>のstruct com_example_Integerと異なり、構造体を型定義しています。</p>
  </desc>
</class>

=== maroontress/maroontress.com/Sanctuary/r1/s2/bar/Thread.xml
<?xml version="1.0" encoding="euc-jp"?>
<!DOCTYPE class SYSTEM "http://maroontress.com/Sanctuary/1.0/sanctuary.dtd" [
  <!ENTITY thisParam '
    <param type="struct @ *" name="thread">
      <desc>Threadクラスのインスタンス</desc>
    </param>
  '>
]>
<class package="bar" name="Thread">
  <namespace/>

  <export type="struct" tag="@">
    <desc><brief>スレッドの実体となる構造体です。</brief><p>不透明な構造体です。</p></desc>
  </export>

  <method name="new">
    &thisParam;

    <param type="void (*#)(struct @ *)" name="run">
      <desc>see bar_Thread_run()</desc>
    </param>

    <desc><brief>スレッドのインスタンスを生成します。</brief></desc>
  </method>

  <method name="start">
    &thisParam;
    <desc><brief>新しいスレッドによるbar_Thread_run()の実行を開始します。</brief></desc>
  </method>

  <abstractmethod name="run">
    &thisParam;
    <desc><brief>スレッドが実行する処理を実装します。</brief></desc>
  </abstractmethod>

  <desc><brief>アブストラクトメソッドの例を提供します。</brief></desc>
</class>
